### ISSUE TITLE
LeySourceEngineProxyServ compiling question

### ISSUE THREAD

**Issue by Taxin2012** [VaasKahnGrim/VaasAntiCheat#1]
Hey! Which dependencies needed for compiling C++ files?
Cuz getting `fatal error: sys/mman.h: No such file or directory` on Ubuntu/Debian.

(Asking cuz author not answering)

**Comment by VaasKahnGrim** [comment]
iirc it should be the same exact dependancies or already handled by the project. unless something has changed since the last time I compiled it. I think when I did I compiled for CentOS 7/8 but can't remember exactly. Are you using WSL, VirtualBox or booting off a USB or something like that for linux compiles? my guess is your linux install might be missing something.

On a side note, you should steal and eat all of Ley's apples for not responding

**Comment by Taxin2012** [comment]
Im trying to compile it on VPS

**Comment by VaasKahnGrim** [comment]
my only guess tbh is that your install is missing something.

Try  running this in the cli for ubuntu `apt-get install build-essential` got this from: https://www.linuxquestions.org/questions/debian-26/sys-mman-h-no-such-file-422414/

**Comment by Taxin2012** [comment]
Trying to compile on CentOS 8, getting error from code:

`error: ‘lastfilewrite’ was not declared in this scope
   auto chrono_milliseconds = std::chrono::duration_cast<std::chrono::milliseconds>(curtime - lastfilewrite);`

**Comment by VaasKahnGrim** [comment]
does it give a specific file and line where that error occured? I'll take a look when I can

**Comment by Taxin2012** [comment]
![image](https://user-images.githubusercontent.com/26491089/101870555-eb11ac00-3b92-11eb-8119-e8d6d2b6959c.png)

**Comment by Taxin2012** [comment]
I can give u root to server if u want

**Comment by VaasKahnGrim** [comment]
from what I can tell its because `lastfilewrite` doesn't seem to be declared anywhere prior to it bing used. the only instances of `lastfilewrite` being in it is on line 992 and line 1001, neither of which are declaring it, they both simply attempt to get its value(line 992) or set it(line 1001). but neither actually define it. I also searched in the entire project for `lastfilewrite` and its only ever used in that file.

You could try defining it just above the sendto function as a test to see if it fixes it. Something like this should work I'd guess, been a while since I've touched the chrono:

```cpp
steady_clock::time_point lastfilewrite = 0;
```

**Comment by Taxin2012** [comment]
k, will try

**Comment by Taxin2012** [comment]
![image](https://user-images.githubusercontent.com/26491089/101871959-873cb280-3b95-11eb-9b35-ed436621c2bd.png)

**Comment by VaasKahnGrim** [comment]
ah mybad. one sec. lemme go see what I did in VaasAC for time_points

**Comment by Taxin2012** [comment]
im changed to
steady_clock::time_point lastfilewrite = steady_clock::now();

**Comment by VaasKahnGrim** [comment]
yea thats what I have aswell so should be good to go then

**Comment by VaasKahnGrim** [comment]
actually I have `std::chrono::high_resolution_clock::now();` but either should work

**Comment by Taxin2012** [comment]
now it miss some dependencies >_<
![image](https://user-images.githubusercontent.com/26491089/101872358-29f53100-3b96-11eb-901f-f92ee3e775d0.png)

**Comment by VaasKahnGrim** [comment]
all you should need now are libmaxminddb and curl then :p

**Comment by Taxin2012** [comment]
![image](https://user-images.githubusercontent.com/26491089/101872713-c4557480-3b96-11eb-9c38-0dc8f3132600.png)
lol

**Comment by VaasKahnGrim** [comment]
maybe it needs a non dev version of curl? not real sure tbh

**Comment by Taxin2012** [comment]
will try then

**Comment by Taxin2012** [comment]
![image](https://user-images.githubusercontent.com/26491089/101875816-5b70fb00-3b9c-11eb-8254-b57a8fabf93a.png)
last error >_<

**Comment by VaasKahnGrim** [comment]
make sure libcurl3-dev package is installed, that seems to be the issue with not finding -lcurl

**Comment by Taxin2012** [comment]
holy sht, i finally compiled that crap

was needed:
yum install libcurl-devel-7.61.1-14.el8.i686
yum install glibc-devel.i686 libgcc.i686 libstdc++-devel.i686

**Comment by Taxin2012** [comment]
THANK U SO MUCH

**Comment by VaasKahnGrim** [comment]
no problem, best of luck

**Comment by Taxin2012** [comment]
Also, where to put leyzyrecl.so file? Already tryed put it to main server folder (where "garrysmod" and "bin") and "bin". Still nothing in console.

**Comment by VaasKahnGrim** [comment]
honestly I don't remember, been a good while since I've used the thing
